"""
Excercise for python 

"""
#EXCERCISE 1 LOOPS

#1.1 CREATE A SIMPLE FOR LOOP TO RUN THROUGH AN ARRAY
array = [1,2,3,6,2,8,9,10,14,25]

#1.2 CREATE A SIMPLE PROGRAM TO LOOP THROUGH AN ARRAY AND CHECK IF A CERTAIN VALUE IS PRESENT


#1.3 CREATE A SIMPLE PROGRAM TO LOOP THROUGH AN ARRAY AND CHECK IF A NUMBER IS ODD OR EVEN


#1.4 CREATE A PROGRAM THAT WILL CONTINUE TO RUN IF THE INPUT IS NOT 3

