#TASK  1
#CREATE A WHILE LOOP THAT CONTINUES TO RUN UNTI THE UNSER INSERTS THE LETTER 'q' IN THE INPUT

# TASK 2 
# CREATE A DICTIONARY AND LOOP THROUGH THE KEYS IF A USER GETS A KEY THAT MATCHS A RANGE DISPLAY THE KEY

# #TASK 3 
# CREATE A LOOP THROUGH THE ARRAY AND MULTIPY THE NUMBER IN THE ARRAY BY THEMSELVES